import express from 'express';
import { createServer as createViteServer } from 'vite';
import { GoogleGenAI } from '@google/genai';
import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';

dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const port = 3000;

app.use(express.json({ limit: '10mb' }));

const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY,
  httpOptions: {
    headers: {
      'User-Agent': 'aistudio-build',
    },
  },
});

// Cache for generated audio to save latency and bandwidth
const ttsAudioCache = new Map<string, string>();

// High-fidelity Neural Text-to-Speech API using Gemini Studio Models
app.post('/api/tts', async (req, res) => {
  try {
    const { text, voiceName = 'Kore', stylePrompt } = req.body;
    if (!text || typeof text !== 'string') {
      return res.status(400).json({ error: 'Text is required' });
    }

    const cacheKey = `${voiceName}:${text.slice(0, 300)}:${text.length}`;
    if (ttsAudioCache.has(cacheKey)) {
      return res.json({ audioBase64: ttsAudioCache.get(cacheKey) });
    }

    // Limit single prompt text to reasonable chunk (~800 chars) for fast generation
    const cleanText = text.replace(/[\n\r]+/g, ' ').trim();
    const truncatedText = cleanText.length > 900 ? cleanText.slice(0, 900) + '...' : cleanText;

    const promptText = stylePrompt 
      ? `${stylePrompt}: "${truncatedText}"`
      : `Lee con voz humana natural, cálida, reflexiva y serena en español: "${truncatedText}"`;

    const response = await ai.models.generateContent({
      model: 'gemini-3.8-flash-lite-tts',
      contents: [
        {
          role: 'user',
          parts: [{ text: promptText }],
        },
      ],
      config: {
        responseModalities: ['AUDIO'],
        speechConfig: {
          voiceConfig: {
            // Prebuilt voices: 'Kore', 'Fenrir', 'Aoede', 'Puck', 'Charon'
            prebuiltVoiceConfig: { voiceName: voiceName },
          },
        },
      },
    });

    const base64Audio = response.candidates?.[0]?.content?.parts?.[0]?.inlineData?.data;
    if (!base64Audio) {
      return res.status(500).json({ error: 'No audio generated by model' });
    }

    // Store in cache (cap at 60 items)
    if (ttsAudioCache.size > 60) {
      const firstKey = ttsAudioCache.keys().next().value;
      if (firstKey) ttsAudioCache.delete(firstKey);
    }
    ttsAudioCache.set(cacheKey, base64Audio);

    res.json({ audioBase64: base64Audio });
  } catch (error: any) {
    console.error('Error generating Gemini TTS:', error);
    res.status(500).json({ error: error.message || 'Error generating TTS' });
  }
});

// Mount Vite or serve static dist
async function startServer() {
  if (process.env.NODE_ENV !== 'production') {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: 'spa',
    });
    app.use(vite.middlewares);
  } else {
    app.use(express.static(path.resolve(__dirname, 'dist')));
    app.get('*', (req, res) => {
      res.sendFile(path.resolve(__dirname, 'dist', 'index.html'));
    });
  }

  app.listen(port, '0.0.0.0', () => {
    console.log(`Server running at http://0.0.0.0:${port}`);
  });
}

startServer();
