import express from 'express';
import { createServer as createViteServer } from 'vite';
import { GoogleGenAI } from '@google/genai';
import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';

dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const port = process.env.PORT ? parseInt(process.env.PORT, 10) : 3000;

// Middleware
app.use(express.json({ limit: '10mb' }));

// Validate API key on startup
if (!process.env.GEMINI_API_KEY) {
  console.error('ERROR: GEMINI_API_KEY not set in environment variables');
  console.error('Please configure .env with GEMINI_API_KEY');
  process.exit(1);
}

const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY,
  httpOptions: {
    headers: {
      'User-Agent': 'aistudio-build',
    },
  },
});

// Cache for generated audio to save latency and bandwidth
// Map<cacheKey, { audio: string, timestamp: number }>
const ttsAudioCache = new Map<string, { audio: string; timestamp: number }>();
const CACHE_TTL = 24 * 60 * 60 * 1000; // 24 hours in ms
const MAX_CACHE_SIZE = 100;

// Clean up expired cache entries
setInterval(() => {
  const now = Date.now();
  for (const [key, value] of ttsAudioCache.entries()) {
    if (now - value.timestamp > CACHE_TTL) {
      ttsAudioCache.delete(key);
    }
  }
}, 60 * 60 * 1000); // Every hour

// Health check endpoint
app.get('/health', (req, res) => {
  res.json({ status: 'ok', timestamp: new Date().toISOString() });
});

// High-fidelity Neural Text-to-Speech API using Gemini Studio Models
app.post('/api/tts', async (req, res) => {
  try {
    const { text, voiceName = 'Kore', stylePrompt } = req.body;

    // Validate input
    if (!text || typeof text !== 'string') {
      return res.status(400).json({ error: 'Text is required and must be a string' });
    }

    if (text.trim().length === 0) {
      return res.status(400).json({ error: 'Text cannot be empty' });
    }

    if (text.length > 2000) {
      return res.status(400).json({ error: 'Text exceeds maximum length (2000 characters)' });
    }

    // Validate voice name
    const validVoices = ['Kore', 'Fenrir', 'Aoede', 'Puck', 'Charon'];
    if (!validVoices.includes(voiceName)) {
      return res.status(400).json({ error: `Invalid voice. Must be one of: ${validVoices.join(', ')}` });
    }

    // Create cache key
    const cacheKey = `${voiceName}:${text.slice(0, 100)}:${text.length}`;

    // Check cache first
    const cachedEntry = ttsAudioCache.get(cacheKey);
    if (cachedEntry) {
      console.log(`Cache hit for key: ${cacheKey}`);
      return res.json({ audioBase64: cachedEntry.audio, cached: true });
    }

    // Clean up cache if at capacity
    if (ttsAudioCache.size >= MAX_CACHE_SIZE) {
      const oldestKey = ttsAudioCache.keys().next().value;
      if (oldestKey) {
        ttsAudioCache.delete(oldestKey);
        console.log(`Cache evicted old entry. Current size: ${ttsAudioCache.size}`);
      }
    }

    // Prepare text for generation
    const cleanText = text.replace(/[\n\r]+/g, ' ').trim();
    const truncatedText = cleanText.length > 900 ? cleanText.slice(0, 900) + '...' : cleanText;

    // Build style prompt
    const promptText = stylePrompt 
      ? `${stylePrompt}: "${truncatedText}"`
      : `Lee con voz humana natural, cálida, reflexiva y serena en español: "${truncatedText}"`;

    console.log(`Generating TTS for voice: ${voiceName}, text length: ${truncatedText.length}`);

    // Call Gemini TTS API
    const response = await ai.models.generateContent({
      model: 'gemini-3.8-flash-lite-tts',
      contents: [
        {
          role: 'user',
          parts: [{ text: promptText }],
        },
      ],
      config: {
        responseModalities: ['AUDIO'],
        speechConfig: {
          voiceConfig: {
            prebuiltVoiceConfig: { voiceName: voiceName },
          },
        },
      },
    });

    // Extract audio from response
    const base64Audio = response.candidates?.[0]?.content?.parts?.[0]?.inlineData?.data;
    if (!base64Audio) {
      console.error('No audio data in response');
      return res.status(500).json({ error: 'No audio generated by model' });
    }

    // Store in cache
    ttsAudioCache.set(cacheKey, { audio: base64Audio, timestamp: Date.now() });
    console.log(`Audio cached. Cache size: ${ttsAudioCache.size}`);

    res.json({ audioBase64: base64Audio, cached: false });
  } catch (error: any) {
    console.error('Error generating Gemini TTS:', error);

    // Return appropriate error response
    const statusCode = error.status || 500;
    const errorMessage = error.message || 'Error generating TTS';

    if (statusCode === 429) {
      return res.status(429).json({ error: 'API quota exceeded. Please try again later.' });
    }

    if (statusCode === 503 || statusCode === 502) {
      return res.status(503).json({ error: 'Gemini service temporarily unavailable. Please try again.' });
    }

    res.status(statusCode).json({ error: errorMessage });
  }
});

// 404 handler
app.use((req, res) => {
  res.status(404).json({ error: 'Not found' });
});

// Error handler
app.use((err: any, req: express.Request, res: express.Response, next: express.NextFunction) => {
  console.error('Unhandled error:', err);
  res.status(500).json({ error: 'Internal server error' });
});

// Mount Vite or serve static dist
async function startServer() {
  try {
    if (process.env.NODE_ENV !== 'production') {
      console.log('Running in development mode');
      const vite = await createViteServer({
        server: { middlewareMode: true },
        appType: 'spa',
      });
      app.use(vite.middlewares);
    } else {
      console.log('Running in production mode');
      app.use(express.static(path.resolve(__dirname, 'dist')));
      app.get('*', (req, res) => {
        res.sendFile(path.resolve(__dirname, 'dist', 'index.html'));
      });
    }

    app.listen(port, '0.0.0.0', () => {
      console.log(`✓ Server running at http://localhost:${port}`);
      console.log(`✓ NODE_ENV: ${process.env.NODE_ENV || 'development'}`);
      console.log(`✓ Cache enabled with TTL: ${CACHE_TTL / 1000 / 60 / 60} hours`);
    });
  } catch (err) {
    console.error('Failed to start server:', err);
    process.exit(1);
  }
}

startServer();
